# Generated by Django 4.2.4 on 2023-08-24 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inside', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inside',
            name='image',
            field=models.ImageField(upload_to='inside_image', verbose_name='Фотография внутри портфолио'),
        ),
    ]
