# Generated by Django 4.2.4 on 2023-08-19 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовка главной сорницы')),
                ('title_text', models.CharField(max_length=255, verbose_name='Описание')),
                ('image_homepage', models.ImageField(upload_to='im_home/')),
            ],
            options={
                'verbose_name': 'Натройка главной строницы',
                'verbose_name_plural': 'Натройка главной строницы',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название болга')),
                ('descriptions_blog', models.CharField(max_length=255, verbose_name='Описание блога')),
                ('image', models.ImageField(upload_to='im_blog')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Настройка блога',
            },
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя пользователя')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('subject', models.CharField(max_length=100, verbose_name='Номер телефона')),
                ('message', models.TextField(max_length=255, verbose_name='Введите ваше сообщение')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='Portfoil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_porfoile', models.CharField(max_length=100, verbose_name='Описание портфойле')),
                ('my_image', models.ImageField(upload_to='Фото портфойля')),
                ('discription_image', models.CharField(max_length=50, verbose_name='Описание фото')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'настройка портфойля',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descriptions', models.CharField(max_length=100, verbose_name='descriptions')),
                ('descriptions2', models.CharField(max_length=100, verbose_name='descriptions')),
                ('descriptions3', models.CharField(max_length=100, verbose_name='descriptions')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Настройка сервисов',
            },
        ),
    ]
