# Generated by Django 4.2.4 on 2023-08-22 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_portfoil_portfolio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': '', 'verbose_name_plural': 'Натройка главной строницы'},
        ),
        migrations.AlterModelOptions(
            name='contacts',
            options={'verbose_name': '', 'verbose_name_plural': 'Контакты'},
        ),
    ]
