# Generated by Django 4.2.4 on 2023-09-26 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_contacts_options_remove_contacts_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Заголовка главной строницы'),
        ),
        migrations.AlterField(
            model_name='about',
            name='title_text',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
