# Generated by Django 4.2.4 on 2023-09-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_about_title_alter_about_title_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='title_text',
        ),
        migrations.AlterField(
            model_name='about',
            name='title',
            field=models.TextField(verbose_name='Заголовка главной строницы'),
        ),
    ]
